"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "집중",
//   description: "Generated by create next app",
// };

const data = [
  {
    title: "프로필",
    address: "/myPage",
  },
  {
    title: "찜",
    address: "/myPage/interest",
  },
  {
    title: "게시글",
    address: "/myPage/post",
  },
];

export default function MyPageLayout({ children }: { children: React.ReactNode }) {
  const [selectedMenu, setSelectedMenu] = useState<number | null>(null);

  return (
    <div className="flex justify-center items-center my-24">
      <div className="flex border w-7/12">
        <div className="flex flex-col w-56 border-r">
          {data.map((el, idx) => (
            <div className="py-5" key={idx}>
              <Link
                className={`${selectedMenu === idx ? "border-primary-200 border-l-4 py-4" : ""}`}
                href={el.address}
                onClick={() => setSelectedMenu(idx)}
              >
                <span className="m-5 ">{el.title}</span>
              </Link>
            </div>
          ))}
        </div>
        <div className={`w-full ${inter.className}`}>{children}</div>
      </div>
    </div>
  );
}
