import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "집중",
  description: "Generated by create next app",
};

const data = [
  {
    title: "프로필",
    address: "/myPage",
  },
  {
    title: "찜",
    address: "/myPage/interest",
  },
  {
    title: "게시글",
    address: "/myPage/post",
  },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex justify-center items-center my-32">
      <div className="flex border w-7/12">
        <div className="flex p-6 flex-col w-56 bg-red-600">
          {data.map((el) => (
            <>
              <Link className="pb-4" href={el.address}>
                {el.title}
              </Link>
            </>
          ))}
        </div>
        <div className={` bg-pink-300  w-full ${inter.className}`}>{children}</div>
      </div>
    </div>
  );
}
